- name: add ssh key for simone
  tags: always
  authorized_key:
    user: simone
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOwK3qD3ngvWyHdp3hNTdP1k3MRrS92kAlVPGwb3QTq3 Ansible default"

- name: generate ssh_config file from template
  tags: ssh
  template:
    src: "{{ ssh_template_file }}"
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: restart_sshd
